NH M1.1
zkVerify/cdk-validium-node pull request #2
Opened 2024-03-26 15:32 UTC by MarcoOl94

2024-03-26 18:10 UTC, ysibirski commented on test/config/nginx/templates/default.conf.tmpl
> +    listen 443 ssl;
add new line #85 `http2 off;`

2024-03-26 18:14 UTC, ysibirski requested changes
2 small additions for NGINX config

2024-03-26 18:14 UTC, ysibirski commented on test/config/nginx/templates/default.conf.tmpl
> +    listen 443 ssl;
add new line 113 `http2 off;`

2024-03-27 11:15 UTC, lander86 approved these changes
LGTM

2024-03-27 13:42 UTC, ysibirski commented on test/config/nginx/templates/default.conf.tmpl
> +
Add `http2 off;` after line 113

2024-03-27 13:43 UTC, ysibirski requested changes
One more change under nginx config is required

2024-03-28 13:00 UTC, ysibirski approved these changes
LGTM

2024-03-28 15:41 UTC, merged